name: Quality

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/pnpm-setup

      - run: pnpm run build

      - name: Run tests
        run: pnpm test

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/pnpm-setup

      - name: Run ESLint
        run: pnpm lint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/pnpm-setup

      - run: pnpm run build

      - name: Run typecheck
        run: pnpm typecheck

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/pnpm-setup

      - run: pnpm run build

      - name: Run coverage
        run: pnpm run test:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          name: codecov-umbrella
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          verbose: true
        env:
          CI: true
